/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import Shake, {NetworkTracker, ShakeInvocationEvent} from 'react-native-shake';
import RNFS from 'react-native-fs';

export default class App extends Component<{}> {
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>☆Shake example☆</Text>
                <View style={styles.buttons}>
                    <Button title="start" onPress={() => this.start()}/>
                    <Button title="stop" onPress={() => this.stop()}/>
                    <Button title="attach files" onPress={() => this.attachFiles()}/>
                    <Button title="quick facts" onPress={() => this.setQuickFacts()}/>
                    <Button title="enable blackbox" onPress={() => this.setBlackBoxEnabled()}/>
                    <Button title="disable blackbox" onPress={() => this.setBlackBoxDisabled()}/>
                    <Button title="manual trigger" onPress={() => this.manualTrigger()}/>
                    <Button title="set invocation events" onPress={() => this.setInvocationEvents()}/>
                    <Button title="enable network tracker" onPress={() => this.enableNetworkTracker()}/>
                    <Button title="disable network tracker" onPress={() => this.disableNetworkTracker()}/>
                    <Button title="send network request" onPress={() => this.sendNetworkRequest()}/>
                </View>
            </View>
        );
    }

    start = () => {
        Shake.start();
    };

    stop = () => {
        Shake.stop();
    };

    setInvocationEvents = () => {
        Shake.setInvocationEvents([ShakeInvocationEvent.BUTTON,
            ShakeInvocationEvent.SHAKE,
            ShakeInvocationEvent.SCREENSHOT])
    };

    manualTrigger = () => {
        Shake.manualTrigger();
    };

    setBlackBoxDisabled = () => {
        Shake.setBlackBoxEnabled(false);
    };

    setBlackBoxEnabled = () => {
        Shake.setBlackBoxEnabled(true);
    };

    setQuickFacts = () => {
        Shake.setQuickFacts('Sample quick facts');
    };

    attachFiles = () => {
        let path = RNFS.DocumentDirectoryPath + '/file.txt';
        RNFS.writeFile(path, 'Lorem ipsum dolor sit amet', 'utf8')
            .then((success) => {
                console.log('File written');
                Shake.attachFiles([path]);
            })
            .catch((error) => {
                console.log(error.message);
            });
    };

    enableNetworkTracker = () => {
        NetworkTracker.enable();
    };

    disableNetworkTracker = () => {
        NetworkTracker.disable();
    };

    sendNetworkRequest = () => {
        fetch('https://postman-echo.com/post', {
            method: 'POST',
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                firstParam: 'firstParam',
                secondParam: 'secondParam',
            }),
        }).then(res => {
            alert('Request sent.');
        });
    };

}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    buttons: {
        width: '50%',
        height: '50%',
        justifyContent: 'space-between',
    },
    welcome: {
        fontSize: 32,
        textAlign: 'center',
        margin: 20,
    },
});
