/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import Shake, {ShakeInvocationEvent} from 'react-native-shake';
import RNFS from 'react-native-fs';

export default class App extends Component<{}> {
    componentDidMount() {
        this.createFile();
    }

    createFile = () => {
        let path = RNFS.DocumentDirectoryPath + '/file.txt';
        RNFS.writeFile(path, 'Lorem ipsum dolor sit amet', 'utf8')
            .then((success) => {
                console.log('File written');
            })
            .catch((error) => {
                console.log(error.message);
            });
    };

    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>☆Shake example☆</Text>
                <View style={styles.buttons}>
                    <Button title="start" onPress={() => Shake.start()}/>
                    <Button title="stop" onPress={() => Shake.stop()}/>
                    <Button title="attach files"
                            onPress={() => Shake.attachFiles([RNFS.DocumentDirectoryPath + '/file.txt'])}/>
                    <Button title="quick facts" onPress={() => Shake.setQuickFacts('Sample quick facts')}/>
                    <Button title="enable blackbox" onPress={() => Shake.setBlackBoxEnabled(true)}/>
                    <Button title="disable blackbox" onPress={() => Shake.setBlackBoxEnabled(false)}/>
                    <Button title="manual trigger" onPress={() => Shake.manualTrigger()}/>
                    <Button
                        title="setEvents"
                        onPress={() => {
                            Shake.setInvocationEvents([ShakeInvocationEvent.BUTTON,
                                ShakeInvocationEvent.SHAKE,
                                ShakeInvocationEvent.SCREENSHOT])
                        }
                        }
                    />
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    buttons: {
        width: '50%',
        height: '50%',
        justifyContent: 'space-between',
    },
    welcome: {
        fontSize: 32,
        textAlign: 'center',
        margin: 20,
    },
});
