/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import Shake, {NetworkTracker, ShakeInvocationEvent} from 'react-native-shake';
import RNFS from 'react-native-fs';

export default class App extends Component<{}> {
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>☆Shake example☆</Text>
                <View style={styles.buttons}>
                    <Button title="start" onPress={() => this.start()}/>
                    <Button title="stop" onPress={() => this.stop()}/>
                    <Button title="attach files" onPress={() => this.attachFiles()}/>
                    <Button title="attach files by name" onPress={() => this.attachFilesWithName()}/>
                    <Button title="quick facts" onPress={() => this.setQuickFacts()}/>
                    <Button title="enable blackbox" onPress={() => this.setBlackBoxEnabled()}/>
                    <Button title="disable blackbox" onPress={() => this.setBlackBoxDisabled()}/>
                    <Button title="set invocation events" onPress={() => this.setInvocationEvents()}/>
                    <Button title="enable network tracker" onPress={() => this.enableNetworkTracker()}/>
                    <Button title="disable network tracker" onPress={() => this.disableNetworkTracker()}/>
                    <Button title="send network request" onPress={() => this.sendNetworkRequest()}/>
                </View>
            </View>
        );
    }

    start = () => {
        Shake.start();
    };

    stop = () => {
        Shake.stop();
    };

    setInvocationEvents = () => {
        Shake.setInvocationEvents([ShakeInvocationEvent.BUTTON,
            ShakeInvocationEvent.SHAKE,
            ShakeInvocationEvent.SCREENSHOT])
    };

    setBlackBoxDisabled = () => {
        Shake.setBlackBoxEnabled(false);
    };

    setBlackBoxEnabled = () => {
        Shake.setBlackBoxEnabled(true);
    };

    setQuickFacts = () => {
        Shake.setQuickFacts('Sample quick facts');
    };

    attachFiles = () => {
        this.createFiles().then((files) => {
            if (files) {
                console.log('Files written');
                Shake.attachFiles([
                    files[0],
                    files[1]
                ]);
            } else {
                console.log('Failed to write files');
            }
        });
    };

    attachFilesWithName = () => {
        this.createFiles().then((files) => {
            if (files) {
                console.log('Files written');
                Shake.attachFilesWithName({
                    "name1": files[0],
                    "name2": files[1]
                });
            } else {
                console.log('Failed to write files');
            }
        });
    };

    createFiles = async () => {
        let path1 = RNFS.DocumentDirectoryPath + '/file1.txt';
        let path2 = RNFS.DocumentDirectoryPath + '/file2.txt';

        const file1Created = await this.createFile(path1, "File 1");
        const file2Created = await this.createFile(path2, "File 2");

        console.log(file1Created);

        if (file1Created && file2Created) {
            return [path1, path2];
        }

        return false;
    };

    createFile = async (path, text) => {
        return RNFS.writeFile(path, text, 'utf8').then(() => {
            return true;
        }).catch(() => {
            return false;
        });
    };

    enableNetworkTracker = () => {
        NetworkTracker.enable();
    };

    disableNetworkTracker = () => {
        NetworkTracker.disable();
    };

    sendNetworkRequest = () => {
        fetch('https://postman-echo.com/post', {
            method: 'POST',
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                firstParam: 'firstParam',
                secondParam: 'secondParam',
            }),
        }).then(res => {
            alert('Request sent.');
        });
    };

}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    buttons: {
        width: '50%',
        height: '50%',
        justifyContent: 'space-between',
    },
    welcome: {
        fontSize: 32,
        textAlign: 'center',
        margin: 20,
    },
});
