source 'git@github.com:shakebugs/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

project 'example',
        'DevelopmentDebug' => :debug,
        'DevelopmentRelease' => :release,
        'StagingDebug' => :debug,
        'StagingRelease' => :release,
        'ProductionDebug' => :debug,
        'ProductionRelease' => :release

target 'example' do
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'exampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!(configurations: ['DevelopmentDebug', 'StagingDebug', 'ProductionDebug'])

  post_install do |installer|
    react_native_post_install(installer)
  end
end
